# Generated by Django 5.2.3 on 2025-06-29 21:16

import django.db.models.deletion
import sspagri_back.person.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, sspagri_back.person.models.ModelRolesMixin),
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(blank=True, verbose_name='Title')),
                ('first_name', models.CharField(verbose_name='First name')),
                ('last_name', models.CharField(verbose_name='Last name')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Birth')),
                ('zip_code', models.CharField(blank=True, verbose_name='Zip Code')),
                ('phone', models.CharField(blank=True, verbose_name='Phone Number')),
                ('city', models.CharField(blank=True, null=True, verbose_name='City')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='')),
            ],
            options={
                'verbose_name': 'User information',
                'verbose_name_plural': 'Users information',
            },
        ),
    ]
