# Generated by Django 5.2.3 on 2025-12-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_agriculturalinputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturalinputs',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces')], max_length=30),
        ),
    ]
