# Generated by Django 5.2.3 on 2026-01-03 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_agriculturalinputs_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturalinputs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='agricultural_inputs/'),
        ),
        migrations.AlterField(
            model_name='agriculturalinputs',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
