# Generated by Django 5.2.3 on 2026-01-13 13:27

import django.db.models.deletion
import django.utils.timezone
import koltagri.core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_agriculturalinputs_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agriculturalinputs',
            name='price',
        ),
        migrations.RemoveField(
            model_name='agriculturalinputs',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='agriculturalinputs',
            name='quantity',
        ),
        migrations.CreateModel(
            name='AgriculturalInputPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(editable=False, max_length=255)),
                ('agricultural_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='business.agriculturalinputs')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(koltagri.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(koltagri.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
