# Generated by Django 5.2.3 on 2026-01-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_agriculturalinputusage'),
        ('landplots', '0014_remove_site_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturalinputs',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='landplots.site'),
        ),
        migrations.AddField(
            model_name='expense',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='landplots.site'),
        ),
    ]
