# Generated by Django 5.2.3 on 2025-07-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landplots', '0003_rename_tasks_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('Af', 'Tropical - Floresta tropical (Af)'), ('Am', 'Tropical - Monçônico (Am)'), ('Aw', 'Tropical - Savana com inverno seco (Aw)'), ('As', 'Tropical - Savana com verão seco (As)'), ('BWh', 'Desértico - Quente (BWh)'), ('BWk', 'Desértico - Frio (BWk)'), ('BSh', 'Semiárido - Quente (BSh)'), ('BSk', 'Semiárido - Frio (BSk)'), ('Csa', 'Temperado - Mediterrâneo quente (Csa)'), ('Csb', 'Temperado - Mediterrâneo frio (Csb)'), ('Csc', 'Temperado - Mediterrâneo muito frio (Csc)'), ('Cfa', 'Temperado - Subtropical úmido (Cfa)'), ('Cfb', 'Temperado - Oceânico (Cfb)'), ('Cfc', 'Temperado - Oceânico frio (Cfc)'), ('Dsa', 'Continental - Verão quente, seco (Dsa)'), ('Dsb', 'Continental - Verão ameno, seco (Dsb)'), ('Dsc', 'Continental - Verão curto, seco (Dsc)'), ('Dsd', 'Continental - Invernos rigorosos, seco (Dsd)'), ('Dfa', 'Continental - Verão quente (Dfa)'), ('Dfb', 'Continental - Verão ameno (Dfb)'), ('Dfc', 'Continental - Subártico (Dfc)'), ('Dfd', 'Continental - Invernos extremos (Dfd)'), ('ET', 'Polar - Tundra (ET)'), ('EF', 'Polar - Geleiras eternas (EF)')], max_length=3, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plantspecies',
            name='ideal_weather',
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='climate_zones',
            field=models.ManyToManyField(to='landplots.climatezone'),
        ),
    ]
