# Generated by Django 5.2.3 on 2025-07-17 11:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landplots', '0005_remove_sitemembership_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cultivation',
        ),
        migrations.AddField(
            model_name='cultivation',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='cultivationplant',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='site',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='task',
            name='cultivation_plant',
            field=models.ManyToManyField(to='landplots.cultivationplant', verbose_name=''),
        ),
    ]
