# Generated by Django 5.2.3 on 2025-07-14 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('landplots', '0004_climatezone_remove_plantspecies_ideal_weather_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sitemembership',
            name='unique_together',
        ),
        migrations.AddConstraint(
            model_name='sitemembership',
            constraint=models.UniqueConstraint(fields=('user', 'site'), name='unique_user_site'),
        ),
    ]
