# Generated by Django 5.2.3 on 2025-08-15 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('landplots', '0006_remove_task_cultivation_cultivation_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='site',
            name='unique_name_number',
        ),
        migrations.RemoveField(
            model_name='site',
            name='number',
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
