# Generated by Django 5.2.3 on 2025-10-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landplots', '0007_remove_site_unique_name_number_remove_site_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivationplant',
            name='new_plantation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cultivationplant',
            name='planting_day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
