# Generated by Django 5.2.3 on 2025-10-28 22:45

import django.db.models.deletion
import koltagri.core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landplots', '0008_cultivationplant_new_plantation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cultivationplant',
            name='area',
        ),
        migrations.RemoveField(
            model_name='cultivationplant',
            name='harvest_day',
        ),
        migrations.RemoveField(
            model_name='cultivationplant',
            name='planting_day',
        ),
        migrations.CreateModel(
            name='PlantingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('event_type', models.CharField(choices=[('thinning', 'Desbaste'), ('pruning', 'Poda'), ('pollination', 'Polinização'), ('fertilization', 'Fertilização'), ('pest_control', 'Controle de Pragas')], max_length=50, verbose_name='Tipo de Evento')),
                ('event_date', models.DateField(verbose_name='Data do Evento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Anotações')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(koltagri.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('cultivation_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='landplots.cultivationplant', verbose_name='Plantio')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(koltagri.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Evento de Plantio',
                'verbose_name_plural': 'Eventos de Plantio',
                'ordering': ['event_date'],
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
