# Generated by Django 5.2.3 on 2025-12-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landplots', '0009_remove_cultivation_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantspecies',
            name='luminosity_needs',
            field=models.CharField(choices=[('full_sun', 'Sol Pleno'), ('partial_shade', 'Meia Sombra'), ('full_shade', 'Sombra Total')], default='partial_shade', max_length=15),
        ),
    ]
