# Generated by Django 5.2.3 on 2025-12-30 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landplots', '0010_plantspecies_luminosity_needs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivationplant',
            name='new_plantation',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemembership',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='landplots.site'),
        ),
        migrations.AlterField(
            model_name='sitemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
