# Generated by Django 5.2.3 on 2026-01-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landplots', '0012_alter_cultivation_uuid_alter_cultivationplant_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivation',
            name='area',
        ),
    ]
