# Generated by Django 5.2.3 on 2026-01-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landplots', '0013_remove_cultivation_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='area',
        ),
    ]
