# Generated by Django 5.2.3 on 2026-01-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landplots', '0014_remove_site_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
