# Generated by Django 5.2.3 on 2026-01-23 13:02

import django.db.models.deletion
import koltagri.core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landplots', '0015_cultivation_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestCultivationPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('harvest_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('unity', models.CharField(choices=[('kg', 'Quilograma'), ('g', 'Grama'), ('tonne', 'Tonelada'), ('l', 'Litro'), ('unit', 'Unidade')], default='kg', max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(koltagri.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('cultivation_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='landplots.cultivationplant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(koltagri.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
