# Generated by Django 5.2.3 on 2026-01-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landplots', '0016_harvestcultivationplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantspecies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plant_species/'),
        ),
    ]
