# Generated by Django 5.2.3 on 2026-01-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteinvite'),
        ('person', '0003_alter_userinformation_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name=''),
        ),
    ]
