# Generated by Django 5.2.3 on 2026-01-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_userinformation_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='zip_code',
            field=models.CharField(blank=True, null=True, verbose_name='Zip Code'),
        ),
    ]
