# Generated by Django 5.2.3 on 2025-11-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('task', 'Anexo da Tarefa'), ('completion', 'Anexo de Conclusão')], default='task', max_length=20),
        ),
    ]
