# Generated by Django 5.2.3 on 2025-11-26 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landplots', '0009_remove_cultivation_quantity_and_more'),
        ('tasks', '0003_attachment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='plant_species',
            field=models.ManyToManyField(to='landplots.plantspecies', verbose_name='espécies de plantas'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
