# Generated by Django 5.2.3 on 2025-11-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_plant_species_task_priority_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='plant_species',
        ),
    ]
