# Generated by Django 5.2.3 on 2025-12-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_agriculturalinputs'),
        ('landplots', '0009_remove_cultivation_quantity_and_more'),
        ('tasks', '0006_taskcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='supplies',
            field=models.ManyToManyField(blank=True, null=True, to='business.agriculturalinputs', verbose_name='insumos agrícolas'),
        ),
        migrations.AlterField(
            model_name='task',
            name='cultivation_plant',
            field=models.ManyToManyField(blank=True, null=True, to='landplots.cultivationplant', verbose_name='cultivo da planta'),
        ),
    ]
