# Generated by Django 5.2.3 on 2025-12-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_supplies_alter_task_cultivation_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='send_at',
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
