# Generated by Django 5.2.3 on 2025-12-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_attachment_send_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_in',
            new_name='due_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='start_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
