# Generated by Django 5.2.3 on 2025-12-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_agriculturalinputs_unit'),
        ('landplots', '0010_plantspecies_luminosity_needs'),
        ('tasks', '0009_rename_end_in_task_due_date_alter_task_start_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cultivation_plant',
            field=models.ManyToManyField(blank=True, to='landplots.cultivationplant', verbose_name='cultivo da planta'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='supplies',
            field=models.ManyToManyField(blank=True, to='business.agriculturalinputs', verbose_name='insumos agrícolas'),
        ),
    ]
