# Generated by Django 5.2.3 on 2025-12-30 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landplots', '0011_alter_cultivationplant_new_plantation_and_more'),
        ('tasks', '0010_alter_task_cultivation_plant_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='landplots.site'),
        ),
    ]
