# Generated by Django 5.2.3 on 2025-12-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
